export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

export const REQUEST_LOADING = 'REQUEST_LOADING';
export const COMPLETE_LOADING = 'COMPLETE_LOADING';
export const IDLE_LOADING = 'IDLE_LOADING';

export const UPDATE_LIKES = 'UPDATE_LIKES';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const GET_MORE_COMMENTS = 'GET_MORE_COMMENTS';

export const UPDATE_LIKES_COMMENT = 'UPDATE_LIKES_COMMENT';
export const UPDATE_LIKES_REPLY = 'UPDATE_LIKES_REPLY';
export const ADD_REPLY_COMMENT = 'ADD_REPLY_COMMENT';
export const REMOVE_REPLY_COMMENT = 'REMOVE_REPLY_COMMENT';

export const NOTIFICATION_LOADED = 'NOTIFICATION_LOADED';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const FOLLOWING_NOTIFICATION = 'FOLLOWING_NOTIFICATION';
export const UNFOLLOWING_NOTIFICATION = 'UNFOLLOWING_NOTIFICATION';
export const MAKE_AS_READ_NOTIFICATION = 'MAKE_AS_READ_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';