export const SET_ALERT = 'SET_ALERT';
export const UPDATE_ACTIVE_ALERT = 'UPDATE_ACTIVE_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

export const REQUEST_LOADING = 'REQUEST_LOADING';
export const COMPLETE_LOADING = 'COMPLETE_LOADING';
export const IDLE_LOADING = 'IDLE_LOADING';

export const UPDATE_LIKES = 'UPDATE_LIKES';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const GET_MORE_COMMENTS = 'GET_MORE_COMMENTS';
export const GET_MORE_REPLIES = 'GET_MORE_REPLIES';

export const UPDATE_LIKES_COMMENT = 'UPDATE_LIKES_COMMENT';
export const UPDATE_LIKES_REPLY = 'UPDATE_LIKES_REPLY';
export const ADD_REPLY_COMMENT = 'ADD_REPLY_COMMENT';
export const REMOVE_REPLY_COMMENT = 'REMOVE_REPLY_COMMENT';

export const NOTIFICATION_LOADED = 'NOTIFICATION_LOADED';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const FOLLOWING_NOTIFICATION = 'FOLLOWING_NOTIFICATION';
export const UNFOLLOWING_NOTIFICATION = 'UNFOLLOWING_NOTIFICATION';
export const MAKE_AS_READ_NOTIFICATION = 'MAKE_AS_READ_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const GET_MORE_NOTIFICATION = 'GET_MORE_NOTIFICATION';

export const ADD_POST = 'ADD_POST';
export const GET_POSTS = 'GET_POSTS';
export const GET_LENGTH_POSTS = 'GET_LENGTH_POSTS';
export const GET_MORE_POSTS = 'GET_MORE_POSTS';
export const GET_POST = 'GET_POST';
export const EDIT_POST = 'EDIT_POST';
export const REMOVE_POST = 'REMOVE_POST';
export const HIDE_POST = 'HIDE_POST';
export const RESET_POST = 'RESET_POST';

// Clear prev loading post
export const CLEAR_POST = 'CLEAR_POST';
export const POST_ERROR = 'POST_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const CLEAR_PROFILE = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const GET_GROUPS = 'GET_GROUPS';
export const GET_MORE_GROUPS = 'GET_MORE_GROUPS';
export const GET_GROUP = 'GET_GROUP';
export const CLEAR_GROUP = 'GET_PROFILES';
export const GROUP_ERROR = 'GROUP_ERROR';

export const JOIN_GROUP = 'JOIN_GROUP';
export const UNJOIN_GROUP = 'UNJOIN_GROUP';

export const GET_FRIENDS = 'GET_FRIENDS';
export const GET_REQUEST_FRIENDS = 'GET_REQUEST_FRIENDS';
export const GET_USERS_FRIENDS = 'GET_USERS_FRIENDS';

export const FRIEND_ERROR = 'FRIEND_ERROR';
export const REQUEST_FRIEND = 'REQUEST_FRIEND';
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';
export const UNACCEPT_FRIEND = 'UNACCEPT_FRIEND';

export const GET_MORE_FRIENDS = 'GET_MORE_FRIENDS';
export const GET_MORE_REQUESTS = 'GET_MORE_REQUESTS';
export const GET_MORE_USERS = 'GET_MORE_USERS';
export const RESET_FRIEND = 'RESET_FRIEND';

// Build parts pc - hardwares api
export const GET_HARDWARE_CPU = 'GET_HARDWARE_CPU';
export const GET_HARDWARE_MOTHERBOARD = 'GET_HARDWARE_MOTHERBOARD';
export const GET_HARDWARE_RAM = 'GET_HARDWARE_RAM';
export const GET_HARDWARE_GRAPHICS = 'GET_HARDWARE_GRAPHICS';
export const HARDWARE_ERROR = 'HARDWARE_ERROR';
export const RELOAD_HARDWARE = 'RELOAD_HARDWARE';

// Rating Build Parts
export const GET_BUILD_PARTS = 'GET_BUILD_PARTS';
export const RATING_BUILD_PARTS = 'RATING_BUILD_PARTS';
export const BUILD_PARTS_ERROR = 'BUILD_PARTS_ERROR';
export const LOADING_BUILD_PARTS = 'LOADING_BUILD_PARTS';

// Search User
export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const ERROR_SEARCH = 'ERROR_SEARCH';